### ISSUE TITLE
Provide friendly user feedback if running outside of git repo

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/python-scm-source#2]
The tool should provide some friendly user message when running in a folder without ".git".

Currently it will just spit out the git error message / stack trace.

**Comment by hjacobs** [comment]
Example of current behavior (running in non-git folder):

```
$ scm-source
Generating scm-source.json..fatal: Not a git repository (or any of the parent directories): .git
 EXCEPTION OCCURRED: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128
Traceback (most recent call last):
  File "/usr/local/bin/scm-source", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/scm_source/cli.py", line 11, in main
    locally_modified = generate_scm_source(file, author)
  File "/usr/local/lib/python3.4/dist-packages/scm_source/api.py", line 24, in generate_scm_source
    data = get_scm_source_data(author)
  File "/usr/local/lib/python3.4/dist-packages/scm_source/api.py", line 13, in get_scm_source_data
    rev = get_output(['git', 'rev-parse', 'HEAD'])
  File "/usr/local/lib/python3.4/dist-packages/scm_source/api.py", line 7, in get_output
    raw = subprocess.check_output(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128
```
