### ISSUE TITLE
Unhelpful error message when the remote is not named "origin"

### ISSUE THREAD

**Issue by ePaul** [zalando-stups/python-scm-source#3]
I just did run this script in a git repository, where the remote is not named "origin", but "zalando".
(I often select custom names for the remotes if I suppose to have both the upstream repository and my own one.)

```
$ scm-source 
Generating scm-source.json.. EXCEPTION OCCURRED: Command '['git', 'config', '--get', 'remote.origin.url']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/scm-source", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/scm_source/cli.py", line 11, in main
    locally_modified = generate_scm_source(file, author)
  File "/usr/local/lib/python3.4/dist-packages/scm_source/api.py", line 24, in generate_scm_source
    data = get_scm_source_data(author)
  File "/usr/local/lib/python3.4/dist-packages/scm_source/api.py", line 14, in get_scm_source_data
    url = get_output(['git', 'config', '--get', 'remote.origin.url'])
  File "/usr/local/lib/python3.4/dist-packages/scm_source/api.py", line 7, in get_output
    raw = subprocess.check_output(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['git', 'config', '--get', 'remote.origin.url']' returned non-zero exit status 1
```

I'm not sure what the correct behavior would be (choose a random remote?), but at least this should give a friendlier error message if other remote names are not supported.

**Comment by hjacobs** [comment]
Maybe we could use the "first" remote we find, i.e. to not hardcode "origin" anywhere..

**Comment by hjacobs** [comment]
In that case there would only be the "error" message about not having any remotes.

**Comment by hjacobs** [comment]
Related: #10
